force-app/main/default/objects/Historico_Individual__c/Historico_Individual__c.object-meta.xml
<CustomObject>
    <label>Histórico de consentimiento</label>
    <nameField>
        <displayFormat>HC-{000000000}</displayFormat>
        <label>Nombre de Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de consentimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Acción C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Acción C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Acción C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Acción C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C122__c.field-meta.xml
<CustomField>
    <fullName>Accion_C122__c</fullName>
    <label>Acción C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C122__c.field-meta.xml
<CustomField>
    <fullName>C122__c</fullName>
    <label>C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C111__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C111__c</fullName>
    <label>Fecha y Hora de Captación C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C112__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C112__c</fullName>
    <label>Fecha y Hora de Captación C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C113__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C113__c</fullName>
    <label>Fecha y Hora de Captación C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C114__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C114__c</fullName>
    <label>Fecha y Hora de Captación C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C122__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C122__c</fullName>
    <label>Fecha y Hora de Captación C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>Individual</referenceTo>
    <relationshipLabel>Históricos Individuales</relationshipLabel>
    <relationshipName>Hist_ricos_Individuales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C113__c.field-meta.xml
<CustomField>
    <fullName>Reason_C113__c</fullName>
    <label>Reason C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C111__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C111__c</fullName>
    <label>Sistema (Consumer) C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C112__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C112__c</fullName>
    <label>Sistema (Consumer) C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C113__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C113__c</fullName>
    <label>Sistema (Consumer) C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C114__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C114__c</fullName>
    <label>Sistema (Consumer) C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C122__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C122__c</fullName>
    <label>Sistema (Consumer) C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Accion_C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Accion_C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Accion_C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Accion_C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C122__c.field-meta.xml
<CustomField>
    <fullName>Accion_C122__c</fullName>
    <label>Accion_C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <description>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</description>
    <inlineHelpText>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</inlineHelpText>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <description>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</description>
    <inlineHelpText>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</inlineHelpText>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <description>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</description>
    <inlineHelpText>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</inlineHelpText>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <description>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</description>
    <inlineHelpText>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</inlineHelpText>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C122__c.field-meta.xml
<CustomField>
    <fullName>C122__c</fullName>
    <description>Datos de cliente y audiencias en TV para publicidad personalizada de terceros (C122)</description>
    <inlineHelpText>Datos de cliente y audiencias en TV para publicidad personalizada de terceros (C122)</inlineHelpText>
    <label>C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C111__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C111__c</fullName>
    <label>Fecha y Hora de Captación C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C112__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C112__c</fullName>
    <label>Fecha y Hora de Captación C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C113__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C113__c</fullName>
    <label>Fecha y Hora de Captación C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C114__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C114__c</fullName>
    <label>Fecha y Hora de Captación C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C122__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C122__c</fullName>
    <label>Fecha y Hora de Captación C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C111__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C111__c</fullName>
    <label>Sistema (Consumer) C111</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C112__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C112__c</fullName>
    <label>Sistema (Consumer) C112</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C113__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C113__c</fullName>
    <label>Sistema (Consumer) C113</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C114__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C114__c</fullName>
    <label>Sistema (Consumer) C114</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C122__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C122__c</fullName>
    <label>Sistema (Consumer) C122</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametro_middleware_Marketing__mdt/Parametro_middleware_Marketing__mdt.object-meta.xml
<CustomObject>
    <label>Parametro middleware Marketing</label>
    <pluralLabel>Parametros middleware Marketing</pluralLabel>
</CustomObject>

force-app/main/default/objects/Parametro_middleware_Marketing__mdt/fields/X_api_key_Vindicia__c.field-meta.xml
<CustomField>
    <fullName>X_api_key_Vindicia__c</fullName>
    <label>X api key Vindicia</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Accion_de_Consentimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALTA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA</fullName>
    </customValue>
    <customValue>
        <fullName>MODIFICACION</fullName>
    </customValue>
    <masterLabel>Accion de Consentimiento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Estados_de_consentimientos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Informado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>Aceptado</fullName>
    </customValue>
    <customValue>
        <fullName>Rechazado</fullName>
    </customValue>
    <masterLabel>Estados de consentimientos</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Llamada_Conexion_Middleware.cls
/*Clase para realizar las llamadas de los metodos de Integration_SFDC2EWS_Util
Peng 07/07/2022 */

public with sharing class Llamada_Conexion_Middleware {
    public static String namedCredentialMiddleware = 'Conexi_n_Middleware';
    public static String METHOD_GET = 'GET';
    public static String METHOD_POST = 'POST';
    public static String METHOD_PATCH = 'PATCH';
    public static Parametro_middleware_Marketing__mdt parametro = Parametro_middleware_Marketing__mdt.getInstance('Parametros');

    public static HttpResponse CallApiVersion(String APEX_CLASS, String APEX_METHOD) {
        Map<String, String> mapHeaders = new Map<String, String>();
        //mapHeaders.put('X-Api-Key','AjoSme1Y828ze2BQQSLiv1psHOhveZof7am8P6cQ');
        mapHeaders.put('X-Api-Key', parametro.X_api_key_Vindicia__c);

        HttpResponse respuesta = Integration_SFDC2EWS_Util.callRestWS(namedCredentialMiddleware, 'api/version', METHOD_GET, null, mapHeaders, APEX_CLASS, APEX_METHOD);
        
        return respuesta;
    }

  
    @future(callout=true)
    public static void ActualizacionConsentimientos(String idHistorico) {
        String namedCredentialConsentimiento = '';
        String APEX_CLASS1 = 'Llamada_Conexion_Middleware';
        String APEX_METHOD1 = 'ActualizacionConsentimientos';
        Historico_Individual__c hist = [SELECT id,Persona__c, Persona__r.Id_Externo__c,Fecha_y_Hora_de_Captacion_C111__c,Fecha_y_Hora_de_Captacion_C112__c
                                        ,Fecha_y_Hora_de_Captacion_C113__c,Fecha_y_Hora_de_Captacion_C114__c,Fecha_y_Hora_de_Captacion_C122__c ,Accion_C111__c,
                                        Accion_C112__c,Accion_C113__c,Accion_C114__c,Accion_C122__c,C111__c,C112__c,C113__c,C114__c,C122__c,Sistema_Consumer_C111__c
                                        ,Sistema_Consumer_C112__c,Sistema_Consumer_C113__c,Sistema_Consumer_C114__c,Sistema_Consumer_C122__c,Reason_C111__c
                                        ,Reason_C112__c,Reason_C113__c,Reason_C114__c,Reason_C122__c,Canal_C111__c,Canal_C112__c,Canal_C113__c,Canal_C114__c,
                                        Canal_C122__c
                                        FROM Historico_Individual__c WHERE id= :idHistorico];
        namedCredentialConsentimiento = 'salesforce/accounts/'+hist.Persona__r.Id_Externo__c+'/consents';

        Map<String, String> mapHeaders = new Map<String, String>();
        mapHeaders.put('X-Api-Key', parametro.X_api_key_Vindicia__c);
        Llamada_Conexion_Middleware_util.ListaIndividual request2 = new Llamada_Conexion_Middleware_util.ListaIndividual();
        request2 = Llamada_Conexion_Middleware_util.Consentimientos_body(hist);
        HttpResponse respuesta = Integration_SFDC2EWS_Util.callRestWS(namedCredentialMiddleware, namedCredentialConsentimiento, METHOD_PATCH, request2, mapHeaders, APEX_CLASS1, APEX_METHOD1);
    }

    @future(callout=true)
    public static void ActualizarCodPostalCliente(String idCuenta) {
        String namedCredentialConsentimiento = '';
        String APEX_CLASS1 = 'Llamada_Conexion_Middleware';
        String APEX_METHOD1 = 'ActualizarCodPostalCliente';

        namedCredentialConsentimiento = '/customers/'+idCuenta+'/postal-code';

        Map<String, String> mapHeaders = new Map<String, String>();
        mapHeaders.put('X-Api-Key', parametro.X_api_key_Vindicia__c);
        Llamada_Conexion_Middleware_util.codPostal request2 = new Llamada_Conexion_Middleware_util.codPostal();
        request2 = Llamada_Conexion_Middleware_util.zipCode_body(idCuenta);
        HttpResponse respuesta = Integration_SFDC2EWS_Util.callRestWS(namedCredentialMiddleware, namedCredentialConsentimiento, METHOD_PATCH, request2, mapHeaders, APEX_CLASS1, APEX_METHOD1);
    }
}