force-app/main/default/objects/Historico_Individual__c/Historico_Individual__c.object-meta.xml
<CustomObject>
    <label>Histórico de consentimiento</label>
    <nameField>
        <displayFormat>HC-{000000000}</displayFormat>
        <label>Nombre de Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de consentimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Individual__c/fields/DNI_Individual__c.field-meta.xml
<CustomField>
    <fullName>DNI_Individual__c</fullName>
    <formula>Persona__r.DNI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNI Individual</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HistoricoIndividualHelper.cls
public with sharing class HistoricoIndividualHelper {
      public static void callUpdateConsentimientos(TriggerDispatcher.TriggerParameters tp) {
        String profileName = [SELECT Name FROM Profile WHERE Id =:UserInfo.getProfileId()].Name;
        if(profileName == 'Integration User') {
            return;
        }
        for (Historico_Individual__c historicoIndividual : (List<Historico_Individual__c>)tp.newList) {
            if(historicoIndividual.DNI_Individual__c != null) {
                Llamada_Conexion_Middleware.ActualizacionConsentimientos(historicoIndividual.id);
            }
        }
    }
}