force-app/main/default/objects/Case/fields/Motivo_de_cierre__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_cierre__c</fullName>
    <label>Motivo de cierre</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Razon_de_cierre__c.field-meta.xml
<CustomField>
    <fullName>Razon_de_cierre__c</fullName>
    <description>Campo creado para la petición #29244</description>
    <label>Razón de cierre</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cierre automático</fullName>
            </value>
            <value>
                <fullName>Resuelta incidencia</fullName>
            </value>
            <value>
                <fullName>Resuelta Consulta</fullName>
            </value>
            <value>
                <fullName>Cliente no responde</fullName>
            </value>
            <value>
                <fullName>No es incidencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseMeta__mdt/CaseMeta__mdt.object-meta.xml
<CustomObject>
    <label>CaseMeta</label>
    <pluralLabel>CasesMeta</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseMeta__mdt/fields/IdColaEspera__c.field-meta.xml
<CustomField>
    <fullName>IdColaEspera__c</fullName>
    <label>IdColaEspera</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMeta__mdt/fields/Motivo_de_cierre__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_cierre__c</fullName>
    <label>Motivo de cierre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMeta__mdt/fields/TiempoEnEspera__c.field-meta.xml
<CustomField>
    <fullName>TiempoEnEspera__c</fullName>
    <label>TiempoEnEspera</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchCloseCaseByWaitingTime.cls
// Yordy Martinez Arteaga
// Creado 09/12/2022
global class BatchCloseCaseByWaitingTime implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    public Database.QueryLocator start(Database.BatchableContext bc){

        CaseMeta__mdt metadata = [SELECT IdColaEspera__c, TiempoEnEspera__c, Motivo_de_cierre__c FROM CaseMeta__mdt LIMIT 1];
        Integer TiempoEspera = Integer.valueOf(metadata.TiempoEnEspera__c);
        String propietario = metadata.IdColaEspera__c;
        
        datetime fechaAnterior = System.now().addHours(-TiempoEspera);
        
        //Contrucción de fecha porque el formato no es el adecuado
        String anno = String.valueOf(fechaAnterior.year());
        String mes = String.valueOf(fechaAnterior.month());
        if(mes.length() <= 1) {
            mes = '0' + mes;    
        }
        String dia = String.valueOf(fechaAnterior.day());
        if(dia.length() <= 1) {
            dia = '0' + dia;    
        }

        String fechaLimite = anno + '-' + mes + '-' + dia + 'T00:00:00Z'; //2022-11-25T07:35:46.000+0000
    
        return Database.getQueryLocator('SELECT Id FROM Case WHERE Status = \'On Hold\' AND OwnerId =\''+ propietario +'\' AND LastModifiedDate < '+ fechaLimite );
    }
    
 
    
    public void execute(Database.BatchableContext bc, List<Case> scope){
        List<Case> listaATratar = new List<Case>();
        if(scope != null){
            CaseMeta__mdt metadata = CaseMeta__mdt.getInstance('Case1');

            for(Case c : scope){
                Case caso = new Case();
                caso.Id = c.Id;
                caso.Status = 'Closed';
                caso.Razon_de_cierre__c = 'Cliente no responde';
                caso.Motivo_de_cierre__c = metadata.Motivo_de_cierre__c;
                listaATratar.add(caso);
            }
    
            if(!listaATratar.isEmpty()){
                update listaATratar;
            }
        }
    }
    public void finish(Database.BatchableContext bc){
        
    }
    global void execute(SchedulableContext sc) {
        BatchCloseCaseByWaitingTime bc = new BatchCloseCaseByWaitingTime();
        Database.executeBatch(bc, 200);
    }
}