force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Nombre de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/String_Aux_1__c.field-meta.xml
<CustomField>
    <fullName>String_Aux_1__c</fullName>
    <label>String Aux 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Método de pago rechazado</fullName>
            </value>
            <value>
                <fullName>Caducidad del método de pago</fullName>
            </value>
            <value>
                <fullName>Modificación de datos personales desde la zona privada de la web</fullName>
            </value>
            <value>
                <fullName>Cambio de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Modificación del medio de pago</fullName>
            </value>
            <value>
                <fullName>Baja de cliente</fullName>
            </value>
            <value>
                <fullName>Sospecho de identidad suplantada</fullName>
            </value>
            <value>
                <fullName>Compra por taquilla</fullName>
            </value>
            <value>
                <fullName>Reactivación de la suscripción</fullName>
            </value>
            <value>
                <fullName>Abono de deuda pendiente</fullName>
            </value>
            <value>
                <fullName>Repudio</fullName>
            </value>
            <value>
                <fullName>Baja de suscripcion</fullName>
                <label>Baja de suscripción</label>
            </value>
            <value>
                <fullName>Codigo de verificacion</fullName>
                <label>Código de verificación</label>
            </value>
            <value>
                <fullName>Error contratación suscripción</fullName>
            </value>
            <value>
                <fullName>Contratación activada</fullName>
            </value>
            <value>
                <fullName>Alta de caso</fullName>
            </value>
            <value>
                <fullName>Apertura de incidencia</fullName>
            </value>
            <value>
                <fullName>Solicitud de baja</fullName>
            </value>
            <value>
                <fullName>Baja por deuda adquirida</fullName>
            </value>
            <value>
                <fullName>Verificación de email</fullName>
            </value>
            <value>
                <fullName>Activación de suscripcion</fullName>
                <isActive>false</isActive>
                <label>Activación de suscripcion</label>
            </value>
            <value>
                <fullName>Baja de usuario</fullName>
                <isActive>false</isActive>
                <label>Baja de usuario</label>
            </value>
            <value>
                <fullName>Contratación TVOD</fullName>
                <isActive>false</isActive>
                <label>Contratación TVOD</label>
            </value>
            <value>
                <fullName>Contratación movistar+lite</fullName>
                <isActive>false</isActive>
                <label>Contratación movistar+lite</label>
            </value>
            <value>
                <fullName>Gestión datos económicos</fullName>
                <isActive>false</isActive>
                <label>Gestión datos económicos</label>
            </value>
            <value>
                <fullName>Gestión de contratos</fullName>
                <isActive>false</isActive>
                <label>Gestión de contratos</label>
            </value>
            <value>
                <fullName>Modificación datos usuario</fullName>
                <isActive>false</isActive>
                <label>Modificación datos usuario</label>
            </value>
            <value>
                <fullName>Recuperación de cuenta</fullName>
                <isActive>false</isActive>
                <label>Recuperación de cuenta</label>
            </value>
            <value>
                <fullName>Registros usuarios</fullName>
                <isActive>false</isActive>
                <label>Registros usuarios</label>
            </value>
            <value>
                <fullName>Sospechosa de identidad suplantada</fullName>
                <isActive>false</isActive>
                <label>Sospechosa de identidad suplantada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/billing_day__c.field-meta.xml
<CustomField>
    <fullName>billing_day__c</fullName>
    <label>Día de facturación</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Card_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Date__c</fullName>
    <label>Fecha de caducidad de tarjeta</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/payment_method__c.field-meta.xml
<CustomField>
    <fullName>payment_method__c</fullName>
    <label>Método de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit_card</fullName>
                <label>Tarjeta de crédito</label>
            </value>
            <value>
                <fullName>paypal</fullName>
                <label>Usuario Paypal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocasional</fullName>
                <default>true</default>
                <label>Ocasional</label>
            </value>
            <value>
                <fullName>Suscriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContract.cls
// PKF
// Creado 01/09/2022
global class BatchContract implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    public Integer recordsProcessed = 0;
    private String tipo_cliente = 'Suscriptor';
    private String tipo_pago = 'credit_card';
    public Database.QueryLocator start(Database.BatchableContext bc) {

        /**
         * PKF modificación para recuperar los contratos con metodo de pago tarjeta de credito y que caduque el mes siguiente
         * 
         */
        Date nextMonthDate = System.today().addMonths(1);
        String monthString = String.valueOf(nextMonthDate.month()).length() == 1 ? '0' + String.valueOf(nextMonthDate.month()) : String.valueOf(nextMonthDate.month());
        String nextMonthYear = monthString + '/' + String.valueOf(nextMonthDate.year()).substring(2);

        String query = 'SELECT Id, AccountId,billing_day__c,Card_Expiration_Date__c FROM Contract ' +
                        'Where Tipo__c = :tipo_cliente AND payment_method__c = :tipo_pago AND Card_Expiration_Date__c = :nextMonthYear';
        
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Contract> scope){
        List<Alerta__c> AlertaLista = new List<Alerta__c>();
        if(!scope.isEmpty()) {
            for (Contract ContractList : scope) {                
                Alerta__c alerta = new Alerta__c();
                alerta.String_Aux_1__c = String.valueOf(ContractList.billing_day__c.intValue())+'/'+ContractList.Card_Expiration_Date__c;
                alerta.Contract__c = ContractList.id;
                alerta.Tipo__c = 'Caducidad del método de pago';
                alerta.Asunto__c ='Metodo de pago próximo a caducar.';
                alerta.Account__c = ContractList.AccountId;
                AlertaLista.add(alerta);
                recordsProcessed = recordsProcessed + 1;
            }
            insert AlertaLista;
        }
    }
    public void finish(Database.BatchableContext bc){
        /*AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];*/
    }

    global void execute(SchedulableContext sc) {
        BatchContract bc = new BatchContract();
        Database.executeBatch(bc, 200);

        String nextScheduleDate = '0 0 0 ';
        if(System.today().day() == 1) {
            nextScheduleDate += '15 ' + System.today().month() + ' ? ' + System.today().year();
        }
        else if(System.today().day() == 15) {
            Date nextMonthDate = System.today().addMonths(1);
            nextScheduleDate += '1 ' + nextMonthDate.month() + ' ? ' + nextMonthDate.year();
        }
        if(!Test.isRunningTest()) {
            
            System.schedule('ScheduleCaducidadMetodoPagoJob', nextScheduleDate, new BatchContract());
        }
    }
    
}