force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Nombre de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Método de pago rechazado</fullName>
            </value>
            <value>
                <fullName>Caducidad del método de pago</fullName>
            </value>
            <value>
                <fullName>Modificación de datos personales desde la zona privada de la web</fullName>
            </value>
            <value>
                <fullName>Cambio de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Modificación del medio de pago</fullName>
            </value>
            <value>
                <fullName>Baja de cliente</fullName>
            </value>
            <value>
                <fullName>Sospecho de identidad suplantada</fullName>
            </value>
            <value>
                <fullName>Compra por taquilla</fullName>
            </value>
            <value>
                <fullName>Reactivación de la suscripción</fullName>
            </value>
            <value>
                <fullName>Abono de deuda pendiente</fullName>
            </value>
            <value>
                <fullName>Repudio</fullName>
            </value>
            <value>
                <fullName>Baja de suscripcion</fullName>
                <label>Baja de suscripción</label>
            </value>
            <value>
                <fullName>Codigo de verificacion</fullName>
                <label>Código de verificación</label>
            </value>
            <value>
                <fullName>Error contratación suscripción</fullName>
            </value>
            <value>
                <fullName>Contratación activada</fullName>
            </value>
            <value>
                <fullName>Alta de caso</fullName>
            </value>
            <value>
                <fullName>Apertura de incidencia</fullName>
            </value>
            <value>
                <fullName>Solicitud de baja</fullName>
            </value>
            <value>
                <fullName>Baja por deuda adquirida</fullName>
            </value>
            <value>
                <fullName>Verificación de email</fullName>
            </value>
            <value>
                <fullName>Activación de suscripcion</fullName>
                <isActive>false</isActive>
                <label>Activación de suscripcion</label>
            </value>
            <value>
                <fullName>Baja de usuario</fullName>
                <isActive>false</isActive>
                <label>Baja de usuario</label>
            </value>
            <value>
                <fullName>Contratación TVOD</fullName>
                <isActive>false</isActive>
                <label>Contratación TVOD</label>
            </value>
            <value>
                <fullName>Contratación movistar+lite</fullName>
                <isActive>false</isActive>
                <label>Contratación movistar+lite</label>
            </value>
            <value>
                <fullName>Gestión datos económicos</fullName>
                <isActive>false</isActive>
                <label>Gestión datos económicos</label>
            </value>
            <value>
                <fullName>Gestión de contratos</fullName>
                <isActive>false</isActive>
                <label>Gestión de contratos</label>
            </value>
            <value>
                <fullName>Modificación datos usuario</fullName>
                <isActive>false</isActive>
                <label>Modificación datos usuario</label>
            </value>
            <value>
                <fullName>Recuperación de cuenta</fullName>
                <isActive>false</isActive>
                <label>Recuperación de cuenta</label>
            </value>
            <value>
                <fullName>Registros usuarios</fullName>
                <isActive>false</isActive>
                <label>Registros usuarios</label>
            </value>
            <value>
                <fullName>Sospechosa de identidad suplantada</fullName>
                <isActive>false</isActive>
                <label>Sospechosa de identidad suplantada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clave_encriptacion__c/Clave_encriptacion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Clave_encriptacion</label>
</CustomObject>

force-app/main/default/objects/Clave_encriptacion__c/fields/Clave__c.field-meta.xml
<CustomField>
    <fullName>Clave__c</fullName>
    <label>Clave</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clave_encriptacion__c/fields/Tiempo_validez_URL__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_validez_URL__c</fullName>
    <description>Validez de la URL en minutos.</description>
    <inlineHelpText>Validez de la URL en minutos.</inlineHelpText>
    <label>Tiempo validez URL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Correo_nuevo__c.field-meta.xml
<CustomField>
    <fullName>Correo_nuevo__c</fullName>
    <label>Correo nuevo</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/email_de_contrato__c.field-meta.xml
<CustomField>
    <fullName>email_de_contrato__c</fullName>
    <label>Email de contrato</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Email_de_verificacion_enviado__c.field-meta.xml
<CustomField>
    <fullName>Email_de_verificacion_enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para Marketing Cloud</description>
    <label>Email de verificación enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Inicio_de_validez_URL__c.field-meta.xml
<CustomField>
    <fullName>Inicio_de_validez_URL__c</fullName>
    <label>Inicio de validez URL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contract/fields/isEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>isEmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email verificado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IsNewURL__c.field-meta.xml
<CustomField>
    <fullName>IsNewURL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nueva URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocasional</fullName>
                <default>true</default>
                <label>Ocasional</label>
            </value>
            <value>
                <fullName>Suscriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/URL_path_encriptada__c.field-meta.xml
<CustomField>
    <fullName>URL_path_encriptada__c</fullName>
    <label>URL_path_encriptada</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/URL_raiz_verificacion__c.field-meta.xml
<CustomField>
    <fullName>URL_raiz_verificacion__c</fullName>
    <label>URL raiz verificacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/URL_verificacion__c.field-meta.xml
<CustomField>
    <fullName>URL_verificacion__c</fullName>
    <label>URL de verificación</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ContractTriggerHelper.cls
/**
 * @description       : 
 * @author            : alvaro.solana@pkf-attest.es
 * @group             : 
 * @last modified on  : 26-09-2022
 * @last modified by  : alvaro.solana@pkf-attest.es
**/
public with sharing class ContractTriggerHelper {

    public static void actualizarContrato(TriggerDispatcher.TriggerParameters tp) {

        Blob key;
        Set<String> idContratos                     = new Set<String>();
        List<Clave_encriptacion__c> keyList         = new List<Clave_encriptacion__c>();
        
        try {

            //Obtengo la Key del custom settings para la encriptación, si no existe la creo.
            keyList = [ SELECT Clave__c FROM Clave_encriptacion__c LIMIT 1 ];

            if (!keyList.isEmpty()) {
                key = EncodingUtil.base64Decode(keyList[0].Clave__c);
            }else {
                Clave_encriptacion__c claveEncriptacion = new Clave_encriptacion__c();
                key = Crypto.generateAesKey(128);
                claveEncriptacion.Clave__c =  EncodingUtil.base64Encode(key);
                claveEncriptacion.Tiempo_validez_URL__c = 60;
                insert claveEncriptacion;
            }

            //Recorremos los contratos insertados o actualizados.
            
            for (Contract contratoNuevo : (List<Contract>)tp.newList) {
                Contract contratoVersionAnterior;
                if(tp.oldMapp != null) {
                    contratoVersionAnterior = (Contract) tp.oldMapp.get(contratoNuevo.Id);
                }
                if ((contratoNuevo.IsNewURL__c && !contratoVersionAnterior.IsNewURL__c) || contratoVersionAnterior == null)
                {
                    idContratos.add(contratoNuevo.Id);

                    String correoNuevo = contratoNuevo.Correo_nuevo__c;
                    //Si es nuevo
                    if(contratoVersionAnterior == null) {
                        correoNuevo = contratoNuevo.email_de_contrato__c;
                    }
                    String urlVerificacion = contratoNuevo.URL_verificacion__c;

                    String urlSubstringToCrypte = urlVerificacion.SubStringAfter('?') + '&email=' + correoNuevo;

                    contratoNuevo.URL_raiz_verificacion__c = urlVerificacion.substringBefore('?') + '?';
                    contratoNuevo.URL_path_encriptada__c = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(urlSubstringToCrypte)));
                    
                    //Obtengo y encripto el correo
                    String urlCompleta =    contratoNuevo.URL_raiz_verificacion__c + contratoNuevo.URL_path_encriptada__c;
                    contratoNuevo.isEmailVerified__c = false;
                    //contratoNuevo.IsNewURL__c = false;
                    contratoNuevo.URL_verificacion__c = urlCompleta;
                    contratoNuevo.Inicio_de_validez_URL__c = DateTime.now();
                    contratoNuevo.Email_de_verificacion_enviado__c = false;
                }
             }

		}catch (Exception e) 
        {
            System.debug('Catch AfterUpdate [ContractTriggerHelper]');
            System.debug(e.getCause());
            System.debug(e.getMessage());
        }
    }
    public static void crearAlertaVerificacionEmail(TriggerDispatcher.TriggerParameters tp) {
        List<Alerta__c> alertas = new List<Alerta__c>();
        List<Contract> contratos = new List<Contract>();
        for(Contract contrato : (List<Contract>) tp.newList) {
            if(contrato.URL_verificacion__c != null && contrato.Tipo__c =='Suscriptor' && (tp.oldMapp == null || contrato.IsNewURL__c)) {
                Alerta__c alerta = new Alerta__c();
                alerta.Tipo__c = 'Verificación de email';
                alerta.Contract__c = contrato.Id;
                alerta.Account__c = contrato.AccountId;
                alertas.add(alerta);
                contratos.add(new Contract(Id = contrato.Id, IsNewURL__c = false));
            }
        }
        if(!alertas.isEmpty()) {
            insert alertas;
        }
        
        if(!contratos.isEmpty()) {
            update contratos;
        }
    }

    public static void EnvioEmailVerificacion(TriggerDispatcher.TriggerParameters tp) {

        for (Contract contratoNuevo : (List<Contract>)tp.newList) {
            if(!contratoNuevo.Email_de_verificacion_enviado__c && contratoNuevo.IsNewURL__c != null) {
                  //PENG 24/04/2023: esta parte de la llamada se queda comentado, ya se va hacer la funcion via Journey
                //envioEmailMKT(contratoNuevo.Id);
            }
        }
    }
    @future(callout=true)
    public static void envioEmailMKT(Id idContrato) {
   
        LlamadaMarketingCloud LMC = new LlamadaMarketingCloud(idContrato);
        LMC.Send_Email_Triggered();

    }
}