force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Nombre de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Método de pago rechazado</fullName>
            </value>
            <value>
                <fullName>Caducidad del método de pago</fullName>
            </value>
            <value>
                <fullName>Modificación de datos personales desde la zona privada de la web</fullName>
            </value>
            <value>
                <fullName>Cambio de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Modificación del medio de pago</fullName>
            </value>
            <value>
                <fullName>Baja de cliente</fullName>
            </value>
            <value>
                <fullName>Sospecho de identidad suplantada</fullName>
            </value>
            <value>
                <fullName>Compra por taquilla</fullName>
            </value>
            <value>
                <fullName>Reactivación de la suscripción</fullName>
            </value>
            <value>
                <fullName>Abono de deuda pendiente</fullName>
            </value>
            <value>
                <fullName>Repudio</fullName>
            </value>
            <value>
                <fullName>Baja de suscripcion</fullName>
                <label>Baja de suscripción</label>
            </value>
            <value>
                <fullName>Codigo de verificacion</fullName>
                <label>Código de verificación</label>
            </value>
            <value>
                <fullName>Error contratación suscripción</fullName>
            </value>
            <value>
                <fullName>Contratación activada</fullName>
            </value>
            <value>
                <fullName>Alta de caso</fullName>
            </value>
            <value>
                <fullName>Apertura de incidencia</fullName>
            </value>
            <value>
                <fullName>Solicitud de baja</fullName>
            </value>
            <value>
                <fullName>Baja por deuda adquirida</fullName>
            </value>
            <value>
                <fullName>Verificación de email</fullName>
            </value>
            <value>
                <fullName>Activación de suscripcion</fullName>
                <isActive>false</isActive>
                <label>Activación de suscripcion</label>
            </value>
            <value>
                <fullName>Baja de usuario</fullName>
                <isActive>false</isActive>
                <label>Baja de usuario</label>
            </value>
            <value>
                <fullName>Contratación TVOD</fullName>
                <isActive>false</isActive>
                <label>Contratación TVOD</label>
            </value>
            <value>
                <fullName>Contratación movistar+lite</fullName>
                <isActive>false</isActive>
                <label>Contratación movistar+lite</label>
            </value>
            <value>
                <fullName>Gestión datos económicos</fullName>
                <isActive>false</isActive>
                <label>Gestión datos económicos</label>
            </value>
            <value>
                <fullName>Gestión de contratos</fullName>
                <isActive>false</isActive>
                <label>Gestión de contratos</label>
            </value>
            <value>
                <fullName>Modificación datos usuario</fullName>
                <isActive>false</isActive>
                <label>Modificación datos usuario</label>
            </value>
            <value>
                <fullName>Recuperación de cuenta</fullName>
                <isActive>false</isActive>
                <label>Recuperación de cuenta</label>
            </value>
            <value>
                <fullName>Registros usuarios</fullName>
                <isActive>false</isActive>
                <label>Registros usuarios</label>
            </value>
            <value>
                <fullName>Sospechosa de identidad suplantada</fullName>
                <isActive>false</isActive>
                <label>Sospechosa de identidad suplantada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/billing_day__c.field-meta.xml
<CustomField>
    <fullName>billing_day__c</fullName>
    <label>Día de facturación</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Estado_de_suscripcion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_suscripcion__c</fullName>
    <label>Estado de suscripción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Pendiente de Activación</fullName>
            </value>
            <value>
                <fullName>Pendiente de Cancelación</fullName>
            </value>
            <value>
                <fullName>Pendiente de Pausa</fullName>
            </value>
            <value>
                <fullName>Pausada</fullName>
            </value>
            <value>
                <fullName>Suspendida</fullName>
            </value>
            <value>
                <fullName>Eliminada</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Actualizada</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocasional</fullName>
                <default>true</default>
                <label>Ocasional</label>
            </value>
            <value>
                <fullName>Suscriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_Contract_Repesca.cls
// Peng
// Creado 01/09/2022
global class Batch_Contract_Repesca implements Database.Batchable<sObject>, Database.Stateful, Schedulable
{
    public Integer recordsProcessed = 0;
    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date todayDate = System.today();
        Date dentroDe2Dias = todayDate.addDays(2);

        Date UltimoDiaMes = todayDate.addMonths(1).toStartOfMonth().addDays(-1);
        System.debug(UltimoDiaMes);
        String queryBuscarDias;

        if(dentroDe2Dias == UltimoDiaMes) {
            switch on dentroDe2Dias.day() {
                when 28 {
                    System.debug('Es 28'); 
                    queryBuscarDias ='billing_day__c IN (28, 29, 30, 31)';
                }
                when 29 {
                    System.debug('Es 29');
                    queryBuscarDias ='billing_day__c IN (29, 30, 31)';
                }
                when 30 {
                    System.debug('Es 30');
                    queryBuscarDias ='billing_day__c IN (30, 31)';
                }
                when 31 {
                    System.debug('Es 31');
                    queryBuscarDias ='billing_day__c IN (31)';
                }
            }
        }
        else {
            queryBuscarDias = 'billing_day__c = ' + String.valueOf(dentroDe2Dias.day()); 
        }

        String queryStr = 'SELECT Id,AccountId,billing_day__c FROM Contract ' +
                        'Where Tipo__c = \'Suscriptor\' AND  Estado_de_suscripcion__c = \'Pendiente de cancelación\' AND ' + queryBuscarDias;

        return Database.getQueryLocator(
            queryStr
        );
    }
    public void execute(Database.BatchableContext bc, List<Contract> scope){
        List<Alerta__c> AlertaLista = new List<Alerta__c>();

        if(!scope.isEmpty()) {
            for (Contract ContractList : scope) {
                Alerta__c alerta = new Alerta__c();
                alerta.Contract__c = ContractList.id;
                alerta.Tipo__c = 'Repesca de suscriptor';
                alerta.Asunto__c ='Repesca de suscriptor.';
                AlertaLista.add(alerta);
                recordsProcessed = recordsProcessed + 1;
                System.debug('Se ha creado alerta' + alerta.Contract__c);
            }
            insert AlertaLista;
        }
    }
    public void finish(Database.BatchableContext bc){
        /*AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];*/
    }

    global void execute(SchedulableContext sc) {
        Batch_Contract_Repesca bc = new Batch_Contract_Repesca();
        Database.executeBatch(bc, 200);
    }
}