force-app/main/default/objects/Contract/fields/billing_day__c.field-meta.xml
<CustomField>
    <fullName>billing_day__c</fullName>
    <label>Día de facturación</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Card_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Date__c</fullName>
    <label>Fecha de caducidad de tarjeta</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/payment_method__c.field-meta.xml
<CustomField>
    <fullName>payment_method__c</fullName>
    <label>Método de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit_card</fullName>
                <label>Tarjeta de crédito</label>
            </value>
            <value>
                <fullName>paypal</fullName>
                <label>Usuario Paypal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocasional</fullName>
                <default>true</default>
                <label>Ocasional</label>
            </value>
            <value>
                <fullName>Suscriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContractTest.cls
@isTest
private class BatchContractTest {
    @testSetup
    static void setup() {
        List<Account> accounts = new List<Account>();
        List<Contract> contract = new List<Contract>();
        
        for (Integer i=0;i<200;i++) {
            accounts.add(new Account(name='Account '+i, billingcity='Madrid', billingcountry='España',BillingPostalCode='28020'));
        }
        insert accounts;
        
        Date nextMonthDate = System.today().addMonths(1);
        String monthString = String.valueOf(nextMonthDate.month()).length() == 1 ? '0' + String.valueOf(nextMonthDate.month()) : String.valueOf(nextMonthDate.month());
        String nextMonthYear = monthString + '/' + String.valueOf(nextMonthDate.year()).substring(2);

        for (Account account : [select id from account]) {
            contract.add(new Contract(Tipo__c='Suscriptor', payment_method__c='credit_card', accountId=account.id, Card_Expiration_Date__c = nextMonthYear,billing_day__c = 15));
        }

        insert contract;
    }
    @isTest static void test() {
        Date todayDate = System.today();
        String dateDay = String.valueOf(todayDate.addDays(1).day()).length() == 1 ? '0' + String.valueOf(todayDate.addDays(1).day()) : String.valueOf(todayDate.addDays(1).day());
        //Varaible para la clase test
        String CRON_EXP = '0 0 0 * * ? *';
        Test.startTest();
        BatchContract bc = new BatchContract();
        Database.executeBatch(bc);

        //Testeamos el Schedulable para subir la cob3rtura
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BatchContract());
        CronTrigger ct = [SELECT Id, CronJobDetail.name,CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        // Verify the next time the job will run
        String monthStr = String.valueOf(todayDate.month());
        System.assertEquals('testBasicScheduledApex', ct.CronJobDetail.name);

        Test.stopTest();
    }
}