force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/Historico_Individual__c.object-meta.xml
<CustomObject>
    <label>Histórico de consentimiento</label>
    <nameField>
        <displayFormat>HC-{000000000}</displayFormat>
        <label>Nombre de Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de consentimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Acción C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Acción C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Acción C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Acción C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C122__c.field-meta.xml
<CustomField>
    <fullName>Accion_C122__c</fullName>
    <label>Acción C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C122__c.field-meta.xml
<CustomField>
    <fullName>C122__c</fullName>
    <label>C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C111__c.field-meta.xml
<CustomField>
    <fullName>Canal_C111__c</fullName>
    <label>Canal C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C112__c.field-meta.xml
<CustomField>
    <fullName>Canal_C112__c</fullName>
    <label>Canal C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C113__c.field-meta.xml
<CustomField>
    <fullName>Canal_C113__c</fullName>
    <label>Canal C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C114__c.field-meta.xml
<CustomField>
    <fullName>Canal_C114__c</fullName>
    <label>Canal C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C122__c.field-meta.xml
<CustomField>
    <fullName>Canal_C122__c</fullName>
    <label>Canal C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C113__c.field-meta.xml
<CustomField>
    <fullName>Reason_C113__c</fullName>
    <label>Reason C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C114__c.field-meta.xml
<CustomField>
    <fullName>Reason_C114__c</fullName>
    <label>Reason C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C122__c.field-meta.xml
<CustomField>
    <fullName>Reason_C122__c</fullName>
    <label>Reason C122</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Accion_C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Accion_C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Accion_C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Accion_C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/AccountRelationship__c.field-meta.xml
<CustomField>
    <fullName>AccountRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountRelationship</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individuals</relationshipLabel>
    <relationshipName>Individuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individual/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <description>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</description>
    <inlineHelpText>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</inlineHelpText>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <description>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</description>
    <inlineHelpText>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</inlineHelpText>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <description>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</description>
    <inlineHelpText>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</inlineHelpText>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <description>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</description>
    <inlineHelpText>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</inlineHelpText>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C122__c.field-meta.xml
<CustomField>
    <fullName>C122__c</fullName>
    <description>Datos de cliente y audiencias en TV para publicidad personalizada de terceros (C122)</description>
    <inlineHelpText>Datos de cliente y audiencias en TV para publicidad personalizada de terceros (C122)</inlineHelpText>
    <label>C122</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C111__c.field-meta.xml
<CustomField>
    <fullName>Canal_C111__c</fullName>
    <label>Canal C111</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C112__c.field-meta.xml
<CustomField>
    <fullName>Canal_C112__c</fullName>
    <label>Canal C112</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C113__c.field-meta.xml
<CustomField>
    <fullName>Canal_C113__c</fullName>
    <label>Canal C113</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C114__c.field-meta.xml
<CustomField>
    <fullName>Canal_C114__c</fullName>
    <label>Canal C114</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C122__c.field-meta.xml
<CustomField>
    <fullName>Canal_C122__c</fullName>
    <label>Canal C122</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <formula>AccountRelationship__r.DNI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C113__c.field-meta.xml
<CustomField>
    <fullName>Reason_C113__c</fullName>
    <label>Reason C113</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C114__c.field-meta.xml
<CustomField>
    <fullName>Reason_C114__c</fullName>
    <label>Reason C114</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C122__c.field-meta.xml
<CustomField>
    <fullName>Reason_C122__c</fullName>
    <label>Reason C122</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <description>Id Externo del Lead</description>
    <externalId>true</externalId>
    <label>Número de lead Lite</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Accion_de_Consentimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALTA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA</fullName>
    </customValue>
    <customValue>
        <fullName>MODIFICACION</fullName>
    </customValue>
    <masterLabel>Accion de Consentimiento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Canal_Individual.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VRU</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION EN FACTURA</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION POR EMAIL</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION POR SMS</fullName>
    </customValue>
    <customValue>
        <fullName>OFICINA ATENCION COMERCIAL</fullName>
    </customValue>
    <customValue>
        <fullName>TELEFONICO</fullName>
    </customValue>
    <customValue>
        <fullName>TIENDA</fullName>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>APP TV</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA MASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>GDPR</fullName>
    </customValue>
    <customValue>
        <fullName>O2</fullName>
    </customValue>
    <customValue>
        <fullName>NT APP</fullName>
    </customValue>
    <customValue>
        <fullName>OTROS</fullName>
    </customValue>
    <customValue>
        <fullName>C360</fullName>
    </customValue>
    <customValue>
        <fullName>OF. AT. COM. EMAIL</fullName>
        <isActive>false</isActive>
        <label>OF. AT. COM. EMAIL</label>
    </customValue>
    <customValue>
        <fullName>EMAIL</fullName>
        <isActive>false</isActive>
        <label>EMAIL</label>
    </customValue>
    <customValue>
        <fullName>FECEDM</fullName>
        <isActive>false</isActive>
        <label>FECEDM</label>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
        <isActive>false</isActive>
        <label>SMS</label>
    </customValue>
    <customValue>
        <fullName>CARTA</fullName>
        <isActive>false</isActive>
        <label>CARTA</label>
    </customValue>
    <customValue>
        <fullName>WEB</fullName>
        <isActive>false</isActive>
        <label>WEB</label>
    </customValue>
    <customValue>
        <fullName>CIRCULAR</fullName>
        <isActive>false</isActive>
        <label>CIRCULAR</label>
    </customValue>
    <masterLabel>Canal Individual</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Estados_de_consentimientos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Informado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>Aceptado</fullName>
    </customValue>
    <customValue>
        <fullName>Rechazado</fullName>
    </customValue>
    <masterLabel>Estados de consentimientos</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Llamada_Conexion_Middleware_test.cls
@IsTest public with sharing class Llamada_Conexion_Middleware_test {

    @TestSetup
	static void makeData()
	{
    
      Lead leadToCreate =new Lead();

      leadToCreate.LastName ='pedro_mpl_317@hotmail.com';
      leadToCreate.Id_Externo__c='LITE-00Q7Y000008UGQjUAO';
      leadToCreate.Email ='test@gmail.com';
      leadToCreate.Status='';
      leadToCreate.DNI__c ='58741488D';
      leadToCreate.PostalCode='28019';
      insert leadToCreate; 
      leadToCreate.Status='Converted';
      update leadToCreate;
      Account accId =[Select id,Name from Account LIMIT 1];

      List<Historico_Individual__c> historicos1 = [Select Id from Historico_Individual__c];
        if(!historicos1.isEmpty()) {}
      Individual ind = new Individual();
        ind.AccountRelationship__c = accId.id;

        ind.Id_Externo__c='92883874-66S5-46P3-B7D1-143D110B653';
        ind.LastName ='PEPE';
        ind.C111__c ='No Informado';
        ind.C112__c ='No Informado';
        ind.C113__c ='No Informado';
        ind.C114__c ='No Informado';
        ind.C122__c ='No Informado';

        ind.Reason_C111__c ='ACCION COMERCIAL';
        ind.Reason_C112__c ='ACCION COMERCIAL';
        ind.Reason_C113__c ='ACCION COMERCIAL';
        ind.Reason_C114__c ='ACCION COMERCIAL';
        ind.Reason_C122__c ='ACCION COMERCIAL';

        ind.Canal_C111__c ='OTROS';
        ind.Canal_C112__c ='OTROS';
        ind.Canal_C113__c ='OTROS';
        ind.Canal_C114__c ='OTROS';
        ind.Canal_C122__c ='OTROS';
        
        ind.Accion_C111__c='ALTA';
        ind.Accion_C112__c='ALTA';
        ind.Accion_C113__c='ALTA';
        ind.Accion_C114__c='ALTA';
        ind.Accion_C122__c='ALTA';

        ind.Sistema_Consumer_C111__c ='Service Cloud';
        ind.Sistema_Consumer_C112__c ='Service Cloud';
        ind.Sistema_Consumer_C113__c ='Service Cloud';
        ind.Sistema_Consumer_C114__c ='Service Cloud';
        ind.Sistema_Consumer_C122__c ='Service Cloud';

        ind.Canal_Captacion_C111__c = 'C360';   
        ind.Canal_Captacion_C112__c = 'C360';
        ind.Canal_Captacion_C113__c = 'C360';
        ind.Canal_Captacion_C114__c = 'C360';
        ind.Canal_Captacion_C122__c = 'C360';

        insert ind;

        ind.Fecha_y_Hora_de_Captacion_C111__c='29/10/2022, 10:07';
        update ind;

        List<Historico_Individual__c> historicos = [Select Id from Historico_Individual__c];
        if(!historicos.isEmpty()) {}
    }


    @isTest static void testCallout() {

    String Body;
    String NamedCredential;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new LlamadaMock_MiddlewareMethod.LlamadaMock_middleware());
    HttpResponse res = 	Llamada_Conexion_Middleware.CallApiVersion('test', 'method');
 
    Body = res.getBody();
    String expectedValue = '0.0.0';
    System.assertEquals(Body, expectedValue);
    System.assertEquals(200, res.getStatusCode());

    Test.stopTest();

    }
    
    @isTest static void testMethodUtil() {
        String Body;
        Individual ind = [Select id,C111__c,C112__c,C113__c,C114__c,C122__c,Reason_C111__c,Reason_C112__c,
        Reason_C113__c ,Reason_C114__c,Reason_C122__c,Fecha_y_Hora_de_Captacion_C111__c,Fecha_y_Hora_de_Captacion_C112__c
        ,Fecha_y_Hora_de_Captacion_C113__c,Fecha_y_Hora_de_Captacion_C114__c,Fecha_y_Hora_de_Captacion_C122__c from Individual LIMIT 1];
        ind.Fecha_y_Hora_de_Captacion_C111__c='29/10/2022, 10:07';
        ind.Fecha_y_Hora_de_Captacion_C112__c='29/10/2022, 10:07';
        ind.Fecha_y_Hora_de_Captacion_C113__c='29/10/2022, 10:07';
        ind.Fecha_y_Hora_de_Captacion_C114__c='29/10/2022, 10:07';
        ind.Fecha_y_Hora_de_Captacion_C122__c='29/10/2022, 10:07';
        String expectedValue ='{'+
        '"id": "0PK7Y0000046DCkWAM",'+
        ' "success": true,'+
        ' "errors": [],'+
        ' "created": true'+
        ' }';
        Test.setMock(HttpCalloutMock.class, new LlamadaMock_MiddlewareMethod.llamadas_Mock());
        Test.startTest();
        update ind;
        List<Historico_Individual__c> listaHistorico = [SELECT id FROM Historico_Individual__c];
        System.assertEquals(2,listaHistorico.size());
        Test.stopTest();


    }

    @isTest static void editHistorico(){
 
        List<Historico_Individual__c> historicos = [Select Id from Historico_Individual__c];
        if(!historicos.isEmpty()) {}

        Historico_Individual__c HI =[Select Accion_C111__c from Historico_Individual__c LIMIT 1];
        HI.Accion_C111__c='Cambio';
        Test.setMock(HttpCalloutMock.class, new LlamadaMock_MiddlewareMethod.llamadas_Mock());
        Test.startTest();
        update HI;     
        Test.stopTest();

    }
    @isTest static void deleteHistorico(){
  
        Historico_Individual__c HI =[Select Accion_C111__c from Historico_Individual__c LIMIT 1];
        Test.startTest(); 
        delete HI;    
        Test.stopTest();

    }

    @isTest static void editzipCode(){
 
        Account acc = [Select Codigo_Postal__c from Account Limit 1];
        acc.Id_Externo__c  ='92883874-66S5-46P3-B7D1-143D112K9685';
        acc.Codigo_Postal__c = '28931';
        Test.setMock(HttpCalloutMock.class, new LlamadaMock_MiddlewareMethod.LlamadaMock_zipCpde());
        Test.startTest();
        update acc;     
        Test.stopTest();

    }
}