force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/Historico_Individual__c.object-meta.xml
<CustomObject>
    <label>Histórico de consentimiento</label>
    <nameField>
        <displayFormat>HC-{000000000}</displayFormat>
        <label>Nombre de Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de consentimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Acción C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Acción C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Acción C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Acción C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C111__c.field-meta.xml
<CustomField>
    <fullName>Canal_C111__c</fullName>
    <label>Canal C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C112__c.field-meta.xml
<CustomField>
    <fullName>Canal_C112__c</fullName>
    <label>Canal C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C113__c.field-meta.xml
<CustomField>
    <fullName>Canal_C113__c</fullName>
    <label>Canal C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Canal_C114__c.field-meta.xml
<CustomField>
    <fullName>Canal_C114__c</fullName>
    <label>Canal C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_Individual</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C111__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C111__c</fullName>
    <label>Fecha y Hora de Captación C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C112__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C112__c</fullName>
    <label>Fecha y Hora de Captación C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C113__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C113__c</fullName>
    <label>Fecha y Hora de Captación C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Fecha_y_Hora_de_Captacion_C114__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C114__c</fullName>
    <label>Fecha y Hora de Captación C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Reason_C113__c.field-meta.xml
<CustomField>
    <fullName>Reason_C113__c</fullName>
    <label>Reason C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C111__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C111__c</fullName>
    <label>Sistema (Consumer) C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C112__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C112__c</fullName>
    <label>Sistema (Consumer) C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C113__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C113__c</fullName>
    <label>Sistema (Consumer) C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Individual__c/fields/Sistema_Consumer_C114__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C114__c</fullName>
    <label>Sistema (Consumer) C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C111__c.field-meta.xml
<CustomField>
    <fullName>Accion_C111__c</fullName>
    <label>Accion_C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C112__c.field-meta.xml
<CustomField>
    <fullName>Accion_C112__c</fullName>
    <label>Accion_C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C113__c.field-meta.xml
<CustomField>
    <fullName>Accion_C113__c</fullName>
    <label>Accion_C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Accion_C114__c.field-meta.xml
<CustomField>
    <fullName>Accion_C114__c</fullName>
    <label>Accion_C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accion_de_Consentimiento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C111__c.field-meta.xml
<CustomField>
    <fullName>C111__c</fullName>
    <description>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</description>
    <inlineHelpText>Datos de cliente para publicidad de Movistar y empresas del grupo (C111)</inlineHelpText>
    <label>C111</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C112__c.field-meta.xml
<CustomField>
    <fullName>C112__c</fullName>
    <description>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</description>
    <inlineHelpText>Datos de cliente para publicidad personalizada de Movistar y de terceros en TV (C112)</inlineHelpText>
    <label>C112</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C113__c.field-meta.xml
<CustomField>
    <fullName>C113__c</fullName>
    <description>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</description>
    <inlineHelpText>Datos de cliente para cederlos a empresas del grupo para publicidad de Movistar (C113)</inlineHelpText>
    <label>C113</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/C114__c.field-meta.xml
<CustomField>
    <fullName>C114__c</fullName>
    <description>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</description>
    <inlineHelpText>Datos de uso para proteger tráficos anómalos desde tu conexión (Ciberseguridad) (C114)</inlineHelpText>
    <label>C114</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados_de_consentimientos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C111__c.field-meta.xml
<CustomField>
    <fullName>Canal_C111__c</fullName>
    <label>Canal C111</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C112__c.field-meta.xml
<CustomField>
    <fullName>Canal_C112__c</fullName>
    <label>Canal C112</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C113__c.field-meta.xml
<CustomField>
    <fullName>Canal_C113__c</fullName>
    <label>Canal C113</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/Canal_C114__c.field-meta.xml
<CustomField>
    <fullName>Canal_C114__c</fullName>
    <label>Canal C114</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFICINA ATENCION COMERCIAL</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <formula>AccountRelationship__r.DNI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C111__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C111__c</fullName>
    <label>Fecha y Hora de Captación C111</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C112__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C112__c</fullName>
    <label>Fecha y Hora de Captación C112</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C113__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C113__c</fullName>
    <label>Fecha y Hora de Captación C113</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Fecha_y_Hora_de_Captacion_C114__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_de_Captacion_C114__c</fullName>
    <label>Fecha y Hora de Captación C114</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C111__c.field-meta.xml
<CustomField>
    <fullName>Reason_C111__c</fullName>
    <label>Reason C111</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C112__c.field-meta.xml
<CustomField>
    <fullName>Reason_C112__c</fullName>
    <label>Reason C112</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Reason_C113__c.field-meta.xml
<CustomField>
    <fullName>Reason_C113__c</fullName>
    <label>Reason C113</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C111__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C111__c</fullName>
    <label>Sistema (Consumer) C111</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C112__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C112__c</fullName>
    <label>Sistema (Consumer) C112</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C113__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C113__c</fullName>
    <label>Sistema (Consumer) C113</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Sistema_Consumer_C114__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Consumer_C114__c</fullName>
    <label>Sistema (Consumer) C114</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Accion_de_Consentimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALTA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA</fullName>
    </customValue>
    <customValue>
        <fullName>MODIFICACION</fullName>
    </customValue>
    <masterLabel>Accion de Consentimiento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Canal_Individual.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VRU</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION EN FACTURA</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION POR EMAIL</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNICACION POR SMS</fullName>
    </customValue>
    <customValue>
        <fullName>OFICINA ATENCION COMERCIAL</fullName>
    </customValue>
    <customValue>
        <fullName>TELEFONICO</fullName>
    </customValue>
    <customValue>
        <fullName>TIENDA</fullName>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>APP TV</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA MASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>GDPR</fullName>
    </customValue>
    <customValue>
        <fullName>O2</fullName>
    </customValue>
    <customValue>
        <fullName>NT APP</fullName>
    </customValue>
    <customValue>
        <fullName>OTROS</fullName>
    </customValue>
    <customValue>
        <fullName>C360</fullName>
    </customValue>
    <customValue>
        <fullName>OF. AT. COM. EMAIL</fullName>
        <isActive>false</isActive>
        <label>OF. AT. COM. EMAIL</label>
    </customValue>
    <customValue>
        <fullName>EMAIL</fullName>
        <isActive>false</isActive>
        <label>EMAIL</label>
    </customValue>
    <customValue>
        <fullName>FECEDM</fullName>
        <isActive>false</isActive>
        <label>FECEDM</label>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
        <isActive>false</isActive>
        <label>SMS</label>
    </customValue>
    <customValue>
        <fullName>CARTA</fullName>
        <isActive>false</isActive>
        <label>CARTA</label>
    </customValue>
    <customValue>
        <fullName>WEB</fullName>
        <isActive>false</isActive>
        <label>WEB</label>
    </customValue>
    <customValue>
        <fullName>CIRCULAR</fullName>
        <isActive>false</isActive>
        <label>CIRCULAR</label>
    </customValue>
    <masterLabel>Canal Individual</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Estados_de_consentimientos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Informado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>Aceptado</fullName>
    </customValue>
    <customValue>
        <fullName>Rechazado</fullName>
    </customValue>
    <masterLabel>Estados de consentimientos</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Llamada_Conexion_Middleware_util.cls
public with sharing class Llamada_Conexion_Middleware_util {
    public class ListaIndividual{
        public List<consents> consents               { get; set; }

    }

    public class consents {
        public String action			             { get; set; }
        public String legal_entity_id			     { get; set; }
        public String status			             { get; set; }
        public String purpose_id			         { get; set; }
        public String user_prompted			         { get; set; }
        
        public String identifier_tag	    	     { get; set; }
        public String consumer		                 { get; set; }
        public String channel		                 { get; set; }
        public String reason		                 { get; set; }
  
        public identifier identifier                 { get; set; }
        public identifier_parent identifier_parent   { get; set; }
    }

    public class identifier {
        public String id		                     { get; set; }
        public String type		                     { get; set; }

    }
    public class identifier_parent {
        public String id		                     { get; set; }
        public String type		                     { get; set; }

    }

    public class codPostal{
        public String postalCode                       { get; set; }
    }
    // public static ListaIndividual parse(String json){
    //     return System.JSON.serialize(json);
    // }

    public static ListaIndividual Consentimientos_body(Historico_Individual__c individualHistorico) {

        String body = ''; 
        ListaIndividual ListaIndividual = new ListaIndividual();
        listaIndividual.consents = new List<consents>();

       
        //Buscar individual
        Individual individual = [SELECT id, DNI__c, Fecha_y_Hora_de_Captacion_C111__c, Accion_C111__c, C111__c, Sistema_Consumer_C111__c, Canal_C111__c, Reason_C111__c,
                                                    Fecha_y_Hora_de_Captacion_C112__c, Accion_C112__c, C112__c, Sistema_Consumer_C112__c, Canal_C112__c, Reason_C112__c,
                                                    Fecha_y_Hora_de_Captacion_C113__c, Accion_C113__c, C113__c, Sistema_Consumer_C113__c, Canal_C113__c, Reason_C113__c,
                                                    Fecha_y_Hora_de_Captacion_C114__c, Accion_C114__c, C114__c, Sistema_Consumer_C114__c, Canal_C114__c, Reason_C114__c,
                                                    Fecha_y_Hora_de_Captacion_C122__c, Accion_C122__c, C122__c, Sistema_Consumer_C122__c, Canal_C122__c, Reason_C122__c 
                                                    FROM Individual WHERE id =: individualHistorico.Persona__c LIMIT 1];
            consents consents_C111 = new consents();
            consents consents_C112 = new consents();
            consents consents_C113 = new consents();
            consents consents_C114 = new consents();
            consents consents_C122 = new consents();

            boolean activarPicklist1 = false;
            boolean activarPicklist2 = false;
            boolean activarPicklist3 = false;
            boolean activarPicklist4 = false;
            boolean activarPicklist5 = false;

            identifier identifier = new identifier();

            identifier_parent identifier_parent = new identifier_parent();

            //Consentimiento C111
            
            identifier.id = individual.DNI__c;
            identifier.type = 'NIF';

            identifier_parent.id = individual.DNI__c;
            identifier_parent.type = 'NIF';
            consents_C111.legal_entity_id = 'MOVISTAR';
            consents_C112.legal_entity_id = 'MOVISTAR';
            consents_C113.legal_entity_id = 'MOVISTAR';
            consents_C114.legal_entity_id = 'MOVISTAR';
            consents_C122.legal_entity_id = 'MOVISTAR';


            if(individualHistorico.Fecha_y_Hora_de_Captacion_C111__c != individual.Fecha_y_Hora_de_Captacion_C111__c) {
                consents_C111.user_prompted = String.valueOf(System.now());
                consents_C111.identifier_tag = 'LITE';
                consents_C111.purpose_id = 'C111';
                consents_C111.action = individual.Accion_C111__c == null ? 'MODIFICACION' : individual.Accion_C111__c;
                consents_C111.status = individual.C111__c;
                consents_C111.consumer = individual.Sistema_Consumer_C111__c == null ? 'LITE' : individual.Sistema_Consumer_C111__c;
                consents_C111.channel = individual.Canal_C111__c;
                consents_C111.reason = individual.Reason_C111__c;

                consents_C111.identifier = identifier;
                consents_C111.identifier_parent = identifier_parent;

                listaIndividual.consents.add(consents_C111);
                activarPicklist1 = true;
            }
            
            if(individualHistorico.Fecha_y_Hora_de_Captacion_C112__c != individual.Fecha_y_Hora_de_Captacion_C112__c) {

                consents_C112.user_prompted = String.valueOf(System.now());
                consents_C112.identifier_tag = 'LITE';
                consents_C112.purpose_id = 'C112';
                consents_C112.action = individual.Accion_C112__c == null ? 'MODIFICACION' : individual.Accion_C112__c;
                consents_C112.status = individual.C112__c;
                consents_C112.consumer = individual.Sistema_Consumer_C112__c == null ? 'LITE' : individual.Sistema_Consumer_C112__c;
                consents_C112.channel = individual.Canal_C112__c;
                consents_C112.reason = individual.Reason_C112__c;
            
                consents_C112.identifier = identifier;
                consents_C112.identifier_parent = identifier_parent;

                listaIndividual.consents.add(consents_C112);
                activarPicklist2 = true;

            }
            if(individualHistorico.Fecha_y_Hora_de_Captacion_C113__c != individual.Fecha_y_Hora_de_Captacion_C113__c) {

                consents_C113.user_prompted = String.valueOf(System.now());
                consents_C113.identifier_tag = 'LITE';
                consents_C113.purpose_id = 'C113';
                consents_C113.action = individual.Accion_C113__c == null ? 'MODIFICACION' : individual.Accion_C113__c;
                consents_C113.status = individual.C113__c;
                consents_C113.consumer = individual.Sistema_Consumer_C113__c == null ? 'LITE' : individual.Sistema_Consumer_C113__c;
                consents_C113.channel = individual.Canal_C113__c;
                consents_C113.reason = individual.Reason_C113__c;
            
                consents_C113.identifier = identifier;
                consents_C113.identifier_parent = identifier_parent;

                listaIndividual.consents.add(consents_C113);
                activarPicklist3 = true;

            }
            if(individualHistorico.Fecha_y_Hora_de_Captacion_C114__c != individual.Fecha_y_Hora_de_Captacion_C114__c) {

                consents_C114.user_prompted = String.valueOf(System.now());
                consents_C114.identifier_tag = 'LITE';
                consents_C114.purpose_id = 'C114';
                consents_C114.action = individual.Accion_C114__c == null ? 'MODIFICACION' : individual.Accion_C114__c;
                consents_C114.status = individual.C114__c;
                consents_C114.consumer = individual.Sistema_Consumer_C114__c == null ? 'LITE' : individual.Sistema_Consumer_C114__c;
                consents_C114.channel = individual.Canal_C114__c;
                consents_C114.reason = individual.Reason_C114__c;
            
                consents_C114.identifier = identifier;
                consents_C114.identifier_parent = identifier_parent;

                listaIndividual.consents.add(consents_C114);
                activarPicklist4 = true;

            }
            if(individualHistorico.Fecha_y_Hora_de_Captacion_C122__c != individual.Fecha_y_Hora_de_Captacion_C122__c) {

                consents_C122.user_prompted = String.valueOf(System.now());
                consents_C122.identifier_tag = 'LITE';
                consents_C122.purpose_id = 'C122';
                consents_C122.action = individual.Accion_C122__c == null ? 'MODIFICACION' : individual.Accion_C122__c;
                consents_C122.status = individual.C122__c;
                consents_C122.consumer = individual.Sistema_Consumer_C122__c == null ? 'LITE' : individual.Sistema_Consumer_C122__c;
                consents_C122.channel = individual.Canal_C122__c;
                consents_C122.reason = individual.Reason_C122__c;
            
                consents_C122.identifier = identifier;
                consents_C122.identifier_parent = identifier_parent;

                listaIndividual.consents.add(consents_C122);
                activarPicklist5 = true;

            }
                    
            body=  JSON.serialize(listaIndividual);
            body = body.replaceAll('null', '');
            return ListaIndividual;
        
    }

    public static codPostal zipCode_body(String idAcc){
        Account acc = [Select id, Codigo_Postal__c FROM Account where Id_Externo__c =: idAcc];
        codPostal codPostal = new codPostal();
        codPostal.postalCode = acc.Codigo_Postal__c;
        return codPostal;
    }
      
}