force-app/main/default/objects/Account/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Nombre de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/codigo_verificacion__c.field-meta.xml
<CustomField>
    <fullName>codigo_verificacion__c</fullName>
    <label>código verificación</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Método de pago rechazado</fullName>
            </value>
            <value>
                <fullName>Caducidad del método de pago</fullName>
            </value>
            <value>
                <fullName>Modificación de datos personales desde la zona privada de la web</fullName>
            </value>
            <value>
                <fullName>Cambio de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Modificación del medio de pago</fullName>
            </value>
            <value>
                <fullName>Baja de cliente</fullName>
            </value>
            <value>
                <fullName>Sospecho de identidad suplantada</fullName>
            </value>
            <value>
                <fullName>Compra por taquilla</fullName>
            </value>
            <value>
                <fullName>Reactivación de la suscripción</fullName>
            </value>
            <value>
                <fullName>Abono de deuda pendiente</fullName>
            </value>
            <value>
                <fullName>Repudio</fullName>
            </value>
            <value>
                <fullName>Baja de suscripcion</fullName>
                <label>Baja de suscripción</label>
            </value>
            <value>
                <fullName>Codigo de verificacion</fullName>
                <label>Código de verificación</label>
            </value>
            <value>
                <fullName>Error contratación suscripción</fullName>
            </value>
            <value>
                <fullName>Contratación activada</fullName>
            </value>
            <value>
                <fullName>Alta de caso</fullName>
            </value>
            <value>
                <fullName>Apertura de incidencia</fullName>
            </value>
            <value>
                <fullName>Solicitud de baja</fullName>
            </value>
            <value>
                <fullName>Baja por deuda adquirida</fullName>
            </value>
            <value>
                <fullName>Verificación de email</fullName>
            </value>
            <value>
                <fullName>Activación de suscripcion</fullName>
                <isActive>false</isActive>
                <label>Activación de suscripcion</label>
            </value>
            <value>
                <fullName>Baja de usuario</fullName>
                <isActive>false</isActive>
                <label>Baja de usuario</label>
            </value>
            <value>
                <fullName>Contratación TVOD</fullName>
                <isActive>false</isActive>
                <label>Contratación TVOD</label>
            </value>
            <value>
                <fullName>Contratación movistar+lite</fullName>
                <isActive>false</isActive>
                <label>Contratación movistar+lite</label>
            </value>
            <value>
                <fullName>Gestión datos económicos</fullName>
                <isActive>false</isActive>
                <label>Gestión datos económicos</label>
            </value>
            <value>
                <fullName>Gestión de contratos</fullName>
                <isActive>false</isActive>
                <label>Gestión de contratos</label>
            </value>
            <value>
                <fullName>Modificación datos usuario</fullName>
                <isActive>false</isActive>
                <label>Modificación datos usuario</label>
            </value>
            <value>
                <fullName>Recuperación de cuenta</fullName>
                <isActive>false</isActive>
                <label>Recuperación de cuenta</label>
            </value>
            <value>
                <fullName>Registros usuarios</fullName>
                <isActive>false</isActive>
                <label>Registros usuarios</label>
            </value>
            <value>
                <fullName>Sospechosa de identidad suplantada</fullName>
                <isActive>false</isActive>
                <label>Sospechosa de identidad suplantada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/URL_1__c.field-meta.xml
<CustomField>
    <fullName>URL_1__c</fullName>
    <label>URL 1</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/URL_2__c.field-meta.xml
<CustomField>
    <fullName>URL_2__c</fullName>
    <label>URL 2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Correo_nuevo__c.field-meta.xml
<CustomField>
    <fullName>Correo_nuevo__c</fullName>
    <label>Correo nuevo</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Número de contrato Lite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IsNewURL__c.field-meta.xml
<CustomField>
    <fullName>IsNewURL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nueva URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocasional</fullName>
                <default>true</default>
                <label>Ocasional</label>
            </value>
            <value>
                <fullName>Suscriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/URL_verificacion__c.field-meta.xml
<CustomField>
    <fullName>URL_verificacion__c</fullName>
    <label>URL de verificación</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <description>Id Externo del Lead</description>
    <externalId>true</externalId>
    <label>Número de lead Lite</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LlamadaMarketingCloudTest.cls
@IsTest public with sharing class LlamadaMarketingCloudTest {

    @TestSetup
	static void makeData()
	{
        Lead leadToCreate =new Lead();

        leadToCreate.LastName ='pedro_mpl_317@hotmail.com';
        leadToCreate.Id_Externo__c='LITE-00Q7Y000008UGQjUAO';
        leadToCreate.Email ='test@gmail.com';
        leadToCreate.Status='';
        leadToCreate.PostalCode='28019';
        insert leadToCreate; 
        leadToCreate.Status='Converted';
        update leadToCreate;
        Account accId =[Select id,Name from Account LIMIT 1];

        System.debug(leadToCreate);
        Contract contr = new Contract();
        contr.URL_verificacion__c='www.google.es';
        contr.Id_Externo__c='LITE-00Q7Y000008UGQjUAO';
        contr.accountId = accId.id;
        contr.IsNewURL__c=true;
        insert contr;

        Alerta__c alert = new Alerta__c();
        alert.Tipo__c='Codigo de verificacion';
        alert.Account__c=accId.id;
        alert.contract__c=contr.id;
        insert alert;
    }

    @isTest static void LlamadaMarketingCloudContrato() {
    
        Contract contr = [Select name, correo_nuevo__c,URL_verificacion__c,Id_Externo__c,accountId from Contract LIMIT 1];
        contr.name='test@gmail.es';
        contr.correo_nuevo__c='test@gmail.es';
       
        // Call your @future method here.
        update contr;
        System.debug(contr);
        System.debug('ACC ' +contr.id);
        Test.startTest();
 
        Test.setMock(HttpCalloutMock.class,  new LlamadaMock_LlamadaMarketingCloud());
        LlamadaMarketingCloud LMC = new LlamadaMarketingCloud(contr.id);
        HttpResponse res = LMC.Send_Email_Triggered();
        System.debug('Termina Metodo' + res);

        try{
            final String result = string.valueof(res);
            System.assertNotEquals(null, result);
        }
        catch(NullPointerException e) {
            system.debug('ERROR');
        }

        Test.stopTest();
    }

    @isTest static void LlamadaMarketingCloudAlerta() {
        Account accId =[Select id,Name from Account LIMIT 1];
        Contract contrId =[Select id,Name from Contract LIMIT 1];

         Alerta__c alert = new Alerta__c();
        alert.Tipo__c='Codigo de verificacion';
        alert.Account__c=accId.id;
        alert.contract__c=contrId.id;
        alert.codigo_verificacion__c='1234-1234';
        alert.URL_1__c='www.google.es';
        alert.URL_2__c='www.google.es';
        insert alert;
        System.debug('Alerta creado: ' + alert);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class,  new LlamadaMock_LlamadaMarketingCloud());
        
        Test.stopTest();
    }
    
    @isTest static void testContractTriggerHandler(){
        Account accId =[Select id,Name from Account LIMIT 1];

        Contract contr2 =new Contract();
        contr2.URL_verificacion__c='www.google.es';
        contr2.Id_Externo__c='contratoaEliminar';
        contr2.accountId =accId.Id;
        contr2.Name='eliminar';
        insert contr2;
        Test.startTest();
        Contract[] contratoAEliminar =[Select Name From Contract where Name='eliminar'];
        System.debug('Lista Contrato a Eliminar' + contratoAEliminar);
        delete contratoAEliminar;
        Test.stopTest();
    }
    @isTest static void testContractTriggerHandlerEliminar(){

        Test.startTest();

        Contract[] contratoAEliminar =[Select Name From Contract where Name='eliminar'];
        System.debug('Lista Contrato a Eliminar' + contratoAEliminar);
        delete contratoAEliminar;
        Test.stopTest();
    }
    @isTest static void testAlertTriggerHandlerEliminar(){
        Alerta__c[] AlertaActualizar =[Select codigo_verificacion__c From Alerta__c];
        //AlertaActualizar[0].codigo_verificacion__c='1234-324';
        //update AlertaActualizar;
		Test.startTest();
        delete AlertaActualizar;
        Test.stopTest();
    }
    @isTest static void testAlertTriggerHandlerUpdate(){
        Alerta__c[] AlertaActualizar =[Select codigo_verificacion__c From Alerta__c];
        AlertaActualizar[0].codigo_verificacion__c='1234-324';
		Test.startTest();
        update AlertaActualizar;
        Test.stopTest();
    }
}